### ISSUE TITLE
Possible arbitrary code execution in `create_html`

### ISSUE THREAD

**Issue by Chiroyce1** [ajskateboarder/spylt#1]
https://github.com/lemystic/spylt/blob/ea057a821ab4f73c0855b4d01dfc7ddece74ff9d/spylt/builder.py#L61

Use the [subprocess](https://docs.python.org/3/library/subprocess.html) module instead to prevent arbitrary code execution that *could* occur by someone calling 
```py
create_html('hi"; rm -rf ./* #')
```
Here `hi";` escapes the quote and ends the echo command, then `rm -rf ./*` is an example for aribitrary code execution and the `#` makes the rest of the command (`npx rollup --silent...`) a comment and it doesn't execute.  The command that ends up running will be
```bash
echo "hi"; rm -rf ./* #" | npx rollup --silent --config --file ./__buildcache__/bundle.js >/dev/null
```
This is just an example, I did not go through the code to check if the create_html function does accept user input, I am assuming it does.

**Comment by ajskateboarder** [comment]
I'll patch this 😅

By the way, `create_html` is meant to accept this code:
```js
import App from './App.svelte';
const app = new App({ target: document.body });
export default app;
```
which is created by `create_linker` in the `Module` class
https://github.com/lemystic/spylt/blob/ea057a821ab4f73c0855b4d01dfc7ddece74ff9d/spylt/module.py#L32
